"""inicial

Revision ID: 264ba2455774
Revises: 
Create Date: 2022-04-26 21:17:23.635914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264ba2455774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
