"""Ajuste da exclusão do bd

Revision ID: 4c1527ecb78c
Revises: 70661685b49d
Create Date: 2022-05-02 21:28:06.480629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1527ecb78c'
down_revision = '70661685b49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
