"""Correção no relationship

Revision ID: 612441c6fa60
Revises: fa6ec039f7a6
Create Date: 2022-05-08 21:59:08.829939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612441c6fa60'
down_revision = 'fa6ec039f7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
