"""Correção no relationship

Revision ID: 8e6270f5591b
Revises: 612441c6fa60
Create Date: 2022-05-08 22:01:28.093071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6270f5591b'
down_revision = '612441c6fa60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
