"""Correção no relationship

Revision ID: fa6ec039f7a6
Revises: cf9fbfa93a56
Create Date: 2022-05-08 21:55:43.584834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6ec039f7a6'
down_revision = 'cf9fbfa93a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
